### ISSUE TITLE
Not working on production

### ISSUE THREAD

**Issue by ghost** [wazery/vider#2]
For some reason, when I try to upload my project to Heroku it fails to compile the assets in:

```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        I, [2015-09-27T18:11:58.631012 #397]  INFO -- : Writing /tmp/build_35c0b6e9292d66c525fd823ffd1c4e31/public/assets/jquery.vide-bb47cb360e2008d23981c2fed048aa4870c0b85bf28e026750faaacaf73f0748.js
remote:        rake aborted!
remote:        ExecJS::ProgramError: Name expected (line: 2, col: 37, pos: 51)
```

If I compile the assets with `rake --trace assets:precompile` there's no problem at all, but in production the src keep pointing to assets/video.mp4 instead of the compiled one.

**Comment by adamro** [comment]
I have the exact same problem

**Comment by RailsCod3rFuture** [comment]
Has this issue been fixed?

**Comment by ghost** [comment]
I don't think so, @RailsCod3rFuture, I encourage you to use the [original jQuery plugin](https://github.com/VodkaBears/Vide), or try [this one](https://github.com/linnett/backgroundVideo). Is not good to depend on a deprecated/unmaintained gem.

**Comment by RailsCod3rFuture** [comment]
What approach did you take @MrOutis with backgroundVideo? Do you have an example or tutorial for dealing with the asset pipeline. If there's a gem for the JS library, that would be great.
